export default {
  GET_REPOSITORIES_REQUEST: '@github/GET_REPOSITORIES_REQUEST',
  GET_REPOSITORIES_SUCCESS: '@github/GET_REPOSITORIES_SUCCESS',
  GET_STARREDS_REQUEST: '@github/GET_STARREDS_REQUEST',
  GET_STARREDS_SUCCESS: '@github/GET_STARREDS_SUCCESS',
  GET_USER_REQUEST: '@github/GET_USER_REQUEST',
  GET_USER_SUCCESS: '@github/GET_USER_SUCCESS',
};
